### ISSUE TITLE
Multiword nicks never colorize

### ISSUE THREAD

**Issue by emacswatcher** [leathekd/erc-hl-nicks#10]
erc-hl-nicks-highlight-p returns false for all CamelCase or underscore_ etc nicks because the function erc-hl-nicks traverses each message a word at a time so nicks which span words are never found. 

https://github.com/leathekd/erc-hl-nicks/blob/be181920ce6af0ab5d00d1c638e4e598b3998643/erc-hl-nicks.el#L339

**Comment by leathekd** [comment]
Thanks for your report.  Just so you know, as of July 2023, [erc-hl-nicks is now a part of ERC](https://github.com/leathekd/erc-hl-nicks/issues/15).

It won't be released bundled with Emacs until version 30.1 but is now available in ERC on the Emacs [GNU ELPA](https://elpa.gnu.org/packages/erc.html) repository.

This repo should be considered depricated and will be archived once the next version of ERC is released with Emacs but will be kept "live" for now so the Melpa package isn't accidentally removed before the new version is released.

The new implementation looks great.  Give it a shot and if you have any issues or feature requests check the [ERC docs on how to report them](https://www.gnu.org/software/emacs/manual/html_node/erc/Getting-Help-and-Reporting-Bugs.html).

Thanks again.
