### ISSUE TITLE
Channel name doesn't get colorized in modeline on nickname mention

### ISSUE THREAD

**Issue by grolongo** [leathekd/erc-hl-nicks#12]
Hi,

When I'm using ERC without erc-hl-nicks and my nickname gets mentioned somewhere, I get the channel name highlighted in the modeline with a specific color (like red to standout).

After installing erc-hl-nicks, whenever someone mentions my nickname somewhere like before, I do get the channel name in the modeline but with the default color, just like if someone talked in the channel but didn't mention me.

How can I fix this?

Thanks for the help.

ps: let me know if you want me to provide my ERC conf or something else, but I tried with a minimal config and the issue persisted

**Comment by grolongo** [comment]
for reference, you can avoid having the face overriden by erc-hl-nicks by adding this to your init.el:

`(add-to-list 'erc-hl-nicks-skip-faces "erc-current-nick-face" t)`

**Comment by manufactory** [comment]
I also ran into this, maybe add to the README?
