### ISSUE TITLE
erc-hl-nicks gets unconditionally autoloaded  

### ISSUE THREAD

**Issue by manufactory** [leathekd/erc-hl-nicks#14]
Please take this bug report as friendly suggestion :)

The following code, at the very end of `erc-hl-nicks.el`, loads the module, even if it's not added to `erc-modules`. While I understand the good intention, automatically loading code, without the user's consent, may cause unexpected behavior, which is very hard to debug.
```;;;###autoload
(eval-after-load 'erc
  '(progn
     (unless (featurep 'erc-hl-nicks)
       (require 'erc-hl-nicks))
     (add-to-list 'erc-modules 'hl-nicks t)))
```
I just experienced, such a situation: I was debugging why erc-track did not colorize my mode-line, when I'm mentioned on a channel (essentially, I was running into https://github.com/leathekd/erc-hl-nicks/issues/12 ). Even with all erc- and theming customizations disabled, erc-track did not behave as expected. It took a while before I realized that neither my ERC customizations, nor my the caused the issue. Finally, I ended up going line-by-line through my `init.el` and was quite surprised that everything worked as expected, until I executed `(package-initialize)`. `(package-initialize)` autoloaded erc-hl-nicks, which caused the colors to vanish. 

#12

**Comment by leathekd** [comment]
Thanks for your report.  Just so you know, as of July 2023, [erc-hl-nicks is now a part of ERC](https://github.com/leathekd/erc-hl-nicks/issues/15).

It won't be released bundled with Emacs until version 30.1 but is now available in ERC on the Emacs [GNU ELPA](https://elpa.gnu.org/packages/erc.html) repository.

This repo should be considered depricated and will be archived once the next version of ERC is released with Emacs but will be kept "live" for now so the Melpa package isn't accidentally removed before the new version is released.

The new implementation looks great.  Give it a shot and if you have any issues or feature requests check the [ERC docs on how to report them](https://www.gnu.org/software/emacs/manual/html_node/erc/Getting-Help-and-Reporting-Bugs.html).

Thanks again.
