### ISSUE TITLE
Contribute this to ERC itself

### ISSUE THREAD

**Issue by skangas** [leathekd/erc-hl-nicks#15]
Hi there,

This is a very useful package, thanks! Did you ever consider contributing it back to ERC itself so that it would reach more users?

ERC is distributed with Emacs itself, so it would need a copyright assignment from all significant contributors.  AFAICT, that should be only you, as the limit is those that have roughly added 15 lines of code, give or take. You can read more about that here: https://www.gnu.org/licenses/why-assign.html

Other than that, I'm sure the ERC maintainer would be open to discussing exactly how you could maintain it in the same way as now, for example by continuously merging your version into the one that would then be distributed with Emacs.

Thanks again, and looking forward to hearing what you think!

**Comment by mplscorwin** [comment]
Hi, I wanted to bring this up again because a replacement (in case we cannot arrange to include this package in Emacs) has recently been posted to the mailing list.   I hope you have a chance to look and thanks for consideration.

**Comment by leathekd** [comment]
Sorry, this slipped past me, @skangas.  Thanks for the ping, @mplscorwin.  

I'd be happy to contribute.  There aren't any major challenges to copyright assignment from this package itself, but it was originally forked from erc-highlight-nicknames back in 2011 and I don't know the assignment of that code.  If that doesn't pose any problems then I'm happy to assign the copyright and contribute the package into ERC and Emacs.

**Comment by leathekd** [comment]
Email sent!  :rocket:

> There's little left from their work in yours, is our read. WDYT?

Looks like most things have changed over the years but these lines are still the same: https://github.com/leathekd/erc-hl-nicks/blob/master/erc-hl-nicks.el#L208-L226

Just want to make sure I'm being as upfront as possible.  :)

**Comment by mplscorwin** [comment]
Hi again!

I've just received word that the FSF clerk says your CA is done.  Could you glance at the changes in https://lists.gnu.org/archive/html/emacs-erc/2023-06/msg00023.html and sign off or give feedback (preferably on the list)?

Thank you for this enhancement to ERC David!

**Comment by mplscorwin** [comment]
Thank you David!

Context, for completeness: https://lists.gnu.org/archive/html/emacs-erc/2023-07/msg00010.html

**Comment by leathekd** [comment]
Done: https://lists.gnu.org/archive/html/emacs-erc/2023-07/msg00010.html

I gave the patch a read and it looks great.  `erc-nicks` looks like a solid improvement to `erc-hl-nicks` and I think folks will like it.

Once that patch lands I will add a note to the readme here and release one more version of `erc-hl-nicks` that checks `erc-version` or something and alerts the user that `erc-nicks` is the way to go.

**Comment by mplscorwin** [comment]
You rock!  (It was but a moment on the time-scale of Emacs development :D)

**Comment by mplscorwin** [comment]
Now merged https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=9bdc5c62

And available as part of Emacs on GNU DEVEL ELPA: https://elpa.gnu.org/devel/erc.html

**Comment by skangas** [comment]
Good stuff! Perhaps the README should be updated to say that this will be a part of Emacs 30.1.
